version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - jonhoare
  ignore:
  - dependency-name: Microsoft.Extensions.Configuration.Abstractions
    versions:
    - "> 3.1.3"
  - dependency-name: Microsoft.Extensions.Configuration.Binder
    versions:
    - "> 3.1.3"
  - dependency-name: Microsoft.Extensions.Configuration.EnvironmentVariables
    versions:
    - "> 3.1.3"
  - dependency-name: Microsoft.Extensions.Configuration.FileExtensions
    versions:
    - "> 3.1.3"
  - dependency-name: Microsoft.Extensions.Configuration.Json
    versions:
    - "> 3.1.3"
